### ISSUE TITLE
Delete command message

### ISSUE THREAD

**Issue by lightdiscord** [Popcorn-moe/migi#1]
Add an option to auto-delete the message sent to run the command.

On decorators it's gonna look something like:

```js
@command(/^command$/i, {
    name: 'command',
    desc: 'My command',
    deleteMessage: true
})
```

It'll add something like

```js
function command (message) {
    if (deleteMessage && message.deletable) message.delete()
}
```

**Comment by cchudant** [comment]
I like this idea, but why should we change the @command decorator?
I think creating another decorator makes more sense.

(cp #2; same deal)

**Comment by lightdiscord** [comment]
> Definitely, it will also allow the use of restrictions on listeners smiley
> @LightDiscord #3

Same thing here, it allows use on something other than commands
