### ISSUE TITLE
Run command using a mention instead of prefix

### ISSUE THREAD

**Issue by cchudant** [Popcorn-moe/migi#11]
add a configuration option `mentionIsPrefix` to allow the bot to trigger commands when the prefix of the command is the bot's mention

**Comment by lightdiscord** [comment]
Unresolved question, should we still run the command if the option is on and the prefix is the bot's prefix (i.e. `/`) ?

**Comment by cchudant** [comment]
we should enable the developer to disable prefix by setting it to a falsy value -- `''`, `null` or whatever

**Comment by LightDiscord** [comment]
```js
import { prefixMode } from './command'

class Something {

**Comment by lightdiscord** [comment]
I thought of something like this

```js
@command(/^command$/i, {
    name: 'Command',
    desc: 'Description',
    prefix: Mode.MENTION_ONLY
})
```
Where `Mode` is
```js
const Mode = {
    PREFIX: Symbol('Prefix'),
    MENTION: Symbol('Prefix and Mentions'),
    MENTION_ONLY: Symbol('Mentions only')
}
```

**Comment by cchudant** [comment]
this should be configurable not inside the module but in the global config of the bot, no?

**Comment by DeltaEvo** [comment]
I think, we could simplify this a lot
Just let the prefix take an array, of string or functions
```js
prefix: ["/", ({ client }) => `${client.user} `]
```
And let this global setting, be overriden by a command
```js
@command(/^command$/i, {
    name: 'Command',
    desc: 'Description',
    prefix: ["/", ({  client }) => `${client.user} `]
})
```
And that can also be a function
```js
@command(/^command$/i, {
    name: 'Command',
    desc: 'Description',
    prefix: ({ client }) => client.settings.prefix.concat([({ client }) => `${client.user} `])
})
```

**Comment by cchudant** [comment]
we need the length to remove from the message in order to pass it to the regexes
