### ISSUE TITLE
React to comment message

### ISSUE THREAD

**Issue by DeltaEvo** [Popcorn-moe/migi#2]
Add an option to add reactions the message sent to run the command.

On decorators it's gonna look something like:
```js
@command(/^command$/i, {
    name: 'command',
    desc: 'My command',
    react: ':ok_hand:'
})
// or
@command(/^command$/i, {
    name: 'command',
    desc: 'My command',
    react: '👌'
})
```

It'll add something like
```js
function command (message) {
    if (react) {
		message.react(react[0] === ':' ? message.client.emojis.find("name", react.slice(1, -1) : react)
	}
}
```

**Comment by lightdiscord** [comment]
Allow a list to be used for multiple reactions and maybe a helper to convert `:ok_hand:` to `👌`.

**Comment by cchudant** [comment]
I like this idea, but why should we change the @command decorator?
I think creating another decorator makes more sense.

(cp #1; same deal)

**Comment by lightdiscord** [comment]
> Definitely, it will also allow the use of restrictions on listeners smiley
> @LightDiscord #3

Same thing here, it allows use on something other than commands

**Comment by cchudant** [comment]
yeah like in `@on('message')` maybe but i can't think of another use case
the main reason i want it as another decorator is because won't be that used and `@restrictions` on #3 makes more sense as a decorator so let's follow that rule

same thing on #1, i won't duplicate my comment cause i'm lazy
